import "./globals.css";


export const metadata = {
  title: "Spring Tuto",
  description: "Generated by Spring boot and Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full dark flex flex-col bg-black text-neutral-200 h-full">{children}</body>
    </html>
  );
}
